version: '3'
services:
  app:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - 8081:5000
    container_name: python-container
    networks:
      - py-network
    volumes:
      - py_vol:/app
networks:
  py-networks:
    driver: bridge
